[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/total"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/statistics"
  to = "/.netlify/functions/submit"
  status = 200